### ISSUE TITLE
Publish to PyPI & install from PyPI in edx-platform

### ISSUE THREAD

**Issue by aht007** [openedx/blockstore#212]
## Background

This package is currently installed into edx-platform [directly from GitHub](github.com/openedx/edx-platform/tree/master/requirements/edx/github.in). This is non-ideal because:
* GitHub-hosted requirements take significantly longer (> 4x) to install than PyPI-hosted requirements
* GitHub-hosted requirement pins cannot be upgraded using our standard `make upgrade` workflow.

## Request

* Audit this package's `setup.py` to make sure it looks right before publishing. You can test it out by:
  * creating a virtual environment
  * installing package requirements 
  * running `python setup.py sdist bdist_wheel`
  * checking the contents of the generated `dist/` folder. The folder should contain a .tar.gz that can be unpacked, yielding the contents of what would be pushed to PyPI. The unpacked .tar.gz should include all Python source files (other than test files) as well as a LICENSE and any assets/resources needed for the block to work.
* Publish this package to PyPI whenever a release happens.
* Create a release in order to trigger an initial publish to PyPI
* In edx-platform, remove the blockstore GitHub pin from [github.in](https://github.com/openedx/edx-platform/blob/master/requirements/edx/github.in), and add blockstore to [base.in](https://github.com/openedx/edx-platform/blob/master/requirements/edx/base.in), which holds all PyPI-hosted base dependencies. Run `make upgrade` so that the change is reflected in the requirements `*.txt` files.

**Comment by aht007** [comment]
Sub-task of: https://github.com/openedx/xblock-drag-and-drop-v2/issues/299

**Comment by bradenmacdonald** [comment]
@aht007 will you be continuing this work to publish blockstore on PyPI?

**Comment by aht007** [comment]
https://github.com/openedx/blockstore/releases/tag/v1.2.6
`blockstore` has been released to PyPI. `edx-platform` is still using github installation as a PR for installing blockstore from PyPI is still pending review from owning team.

**Comment by kdmccormick** [comment]
Done, thanks all!
