### ISSUE TITLE
[DEPR]: Deployment of Blockstore as an independent service

### ISSUE THREAD

**Issue by kdmccormick** [openedx/blockstore#296]
2024 UPDATE: This was Accepted, but is also superseded by: 

* https://github.com/openedx/blockstore/issues/314

which will remove all of Blockstore and all references to it.

_______________________________

### Proposal Date

2023-10-27

### Target Ticket Acceptance Date

2023-11-10

### Earliest Open edX Named Release Without This Functionality

Redwood

### Rationale

It was decided three years ago that [Blockstore](https://github.com/openedx/blockstore/), an authoring-oriented storage backend, [makes more sense as an installable app than it does as an independently-deployable micro-service](https://github.com/openedx/blockstore/blob/master/decisions/0002-app-not-service.rst).

Since then, it has been both possible to deploy it as a service _and_ install as an application, but this dual-capability comes at the high cost of  [layers of wrapper APIs](https://github.com/openedx/edx-platform/blob/master/openedx/core/lib/blockstore_api/methods.py), [mostly-dead caching code](https://github.com/openedx/edx-platform/blob/master/openedx/core/djangoapps/content_libraries/libraries_index.py), [test suites that are 80% skipped](https://github.com/openedx/edx-platform/blob/master/openedx/core/djangoapps/content_libraries/tests/test_content_libraries.py), and [complicated deployment instructions](https://github.com/openedx/blockstore/tree/master#current-status) leading to [superfluous tooling code](https://github.com/openedx/openedx-tutor-plugins/tree/main/plugins/tutor-contrib-blockstore-filesystem),

### Removal
```[tasklist]
#### Removal Tasks
- [x] In edx-platform: [remove the use_blockstore_app_api toggle](https://docs.openedx.org/projects/edx-platform/en/latest/references/featuretoggles.html#featuretoggle-blockstore.use_blocksto.re_app_api), keeping the "true" codepaths
- [x] In edx-platform: Remove content libraries V2 indexing and related settings.
- [x] In edx-platform: Remove `@skips` on content_libraries tests, which currently rely on Blockstore running as a micro-service. Make sure tests all pass. If some are seriously broken, put `@skip` back in and create follow-up tickets.
- [x] In edx-platform: Remove [blockstore methods wrapper](https://github.com/openedx/edx-platform/blob/master/openedx/core/lib/blockstore_api/methods.py).
- [ ] In edx-platform: Remove the [blockstore_api tests](https://github.com/openedx/edx-platform/tree/master/openedx/core/lib/blockstore_api/tests). If any mixins there are still needed for different tests, move them elsewhere. For example, they could be moved to the content_libraries app, or maybe a test
- [ ] In edx-platform: Remove the [blockstore_api wrapper module](https://github.com/openedx/edx-platform/blob/master/openedx/core/lib/blockstore_api/__init__.py). Replace imports to it with direct imports to the underlying blockstore functions.
- [ ] In edx-platform: In the [content_libraries app](https://github.com/openedx/edx-platform/blob/master/openedx/core/djangoapps/content_libraries)'s tests, there are a few classes [like this one](https://github.com/openedx/edx-platform/blob/aaea6e5/openedx/core/djangoapps/content_libraries/tests/test_content_libraries.py#L1213-L1219) which needlessly delegate out to a mixin. This is leftover from when blockstore was both an app & service. Collapse each mixin's body into its test class.
- [ ] In edx-platform: Move [blockstore db_routers](https://github.com/openedx/edx-platform/blob/master/openedx/core/lib/blockstore_api/db_routers.py) so that the blockstore_api folder can be deleted. Suggested new location: openedx/core/lib/blockstore_db_routers.py
- [ ] ~In blockstore: Update [openedx.yaml](https://github.com/openedx/blockstore~/blob/aca35cafed182b0b28197fdd9427d00bc20742a9/openedx.yaml#L12) so it isn't tagged in release.~
- [ ] ~In blockstore: Clean up the [readme](https://github.com/openedx/blockstore/tree/master#blockstore).~
- [ ] ~In blockstore: Remove all files, Makefile targets, and dotfile lines relating to of devstack, docker, and docker-compose .~
- [ ] ~In blockstore: Remove [settings files](https://github.com/openedx/blockstore/tree/master/blockstore/settings).~
- [ ] ~In blockstore: Remove [wsgi config](https://github.com/openedx/blockstore/blob/master/blockstore/wsgi.py).~
- [ ] ~In blockstore: Look through [base requirements](https://github.com/openedx/blockstore/blob/master/requirements/base.in) and remove any that was there just because it was a micro-service.~
- [ ] ~In blockstore: Update [this catalog-info comment](https://github.com/openedx/blockstore/blob/aca35cafed182b0b28197fdd9427d00bc20742a9/catalog-info.yaml#L17).~
- [ ] ~In blockstore: Do a final sweep of the code and docs to make sure there's nothing left there that's specific to running Blockstore as a service.~
- [ ] In frontend-app-library-authoring: Remove the part of the readme that tells you to run blockstore ("Now set up blockstore. Blockstore...").
- [ ] In edx-platform and tutor: Set configuration defaults so that blockstore (the app) works out-of-the-box using filesystem storage.
- [ ] In openedx-tutor-plugins: remove any parts of the tutor-contrib-blockstore-minio plugin that are now redundant.
- [ ] In openedx-tutor-plugins: remove the tutor-contrib-blockstore-filesystem plugin.
```

### Replacement

**Blockstore will continue to exist and be actively maintained as an installable Django app.**

### Deprecation

No plans to mark deprecation.

### Migration

We will not provide any migration instructions because we are not aware of anyone using Blockstore as a micro-service.

*If we are wrong and you do run Blockstore as a micro-service*, please reach out and we can help you figure out how to merge your Blockstore database into your LMS/CMS database.

**Comment by kdmccormick** [comment]
This has been accepted. The removal will happen during the [current phase](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3820617729/Spec+Memo+Content+Library+Authoring+Experience+V2) or [next phase](https://openedx.atlassian.net/wiki/spaces/OEPM/pages/3854336026/Brief+What+happens+after+the+V2+launch) of the Content Libraries V2 project.

**Comment by kdmccormick** [comment]
First of several: https://github.com/openedx/edx-platform/pull/33765

**Comment by connorhaugh** [comment]
We should also move the django admin tables for the blockstore items to be viewable in the edx-platform django admin.

**Comment by kdmccormick** [comment]
@connorhaugh I have this in my CMS admin (local tutor):
 
![image](https://github.com/openedx/blockstore/assets/3628148/37db5f50-8281-4c90-8534-6bc42e123580)

**Comment by kdmccormick** [comment]
Indexing was removed: https://github.com/openedx/edx-platform/pull/33888

**Comment by kdmccormick** [comment]
@feanil It actually looks like we will be deprecating Blockstore entirely in favor of Learning Core. I will write that up soon and see if there is any dissent.

In the meantime, I recommend that you folks stick with the parts of this ticket that are outside Blockstore repo, as the Blockstore repo itself will probably just be archived. I went ahead and crossed out the Blockstore-repo tasks.

**Comment by feanil** [comment]
Sounds good, thanks @kdmccormick. Is it worth it to update the tutor plugin or should we just leave that alone as that will get removed as well?

**Comment by kdmccormick** [comment]
@feanil I think they're still worth doing because it'll remove some developer complexity as we port V2 libraries from Blockstore to Learning Core in the coming months, but also no big deal if you're not able to get to them. The edx-platform and frontend-app-library-authoring cleanup is the only stuff that I'd say is really important.

**Comment by kdmccormick** [comment]
2024 UPDATE: This was Accepted, but is also superseded by: 

* https://github.com/openedx/blockstore/issues/314

which will remove all of Blockstore and all references to it.

**Comment by kdmccormick** [comment]
Superseded by https://github.com/openedx/public-engineering/issues/238
