### ISSUE TITLE
Relationship to edx-val (Video Abstraction Layer)

### ISSUE THREAD

**Issue by ormsbee** [openedx/blockstore#62]
# Background of VAL Today

We created [edx-val](https://github.com/edx/edx-val) (Video Abstraction Layer) so that centralized video teams could change video content outside the normal draft/publish flow of courseware editing in Studio. The immediate use case was to add multiple resolutions of those videos and enable HLS support for benefit mobile devices. VAL acts as both a REST API and an XBlock runtime service (though it is not formally a service because it predates XBlock runtime services, it operates in the same way). Video metadata in VAL overrides all other settings.

The main problems that I'm aware of are:

1. Inefficient querying: edx-val doesn't keep careful track of what parts of what courses reference which videos, so courseware often makes an excessive number of calls when fetching metadata needed to render Video XBlocks in a sequence.
2. The ownership is muddled for things like subtitle uploads. If two courses use the edx-val videos and upload new subtitles via course import, should VAL allow the update?
3. VAL adds to the soup of different video settings that the `VideoBlock` has to respect. There are now at least three different ways to specify subtitles, for instance.

# Long Term Goal

I believe that it would simplify the overall system if VAL were eventually eliminated and Video became just another kind of content library. This would bring it into line with the same conventions around ownership, versioning, and metadata/tagging that we have planned for other content, and would walk us back from today's position of always treating videos as a special case.  We could still keep the basic outline of VAL's REST API if that's convenient, but change the backing store to Blockstore (I think the value of this is debatable, given that VEDA is the only thing that ever used it).

If that's a reasonable end goal, then the question is how do we make progress towards that world without doing a complete rewrite of the VideoModule?

I'll post a few possible directions in this thread...

**Comment by pdpinch** [comment]
We’ve really struggled with VAL. It doesn’t handle importing the way we expect it to, and it frequently crashes exports. And of course, nothing _actually_ exports video data — which is a needed feature. (Granted, some of this frustration also has to do with the Studio UI). 

The only thing that has been good about VAL is the REST APIs for adding video — so we didn’t have to run VEDA.

**Comment by bradenmacdonald** [comment]
I believe that we can find a way to build on https://github.com/edx/edx-platform/pull/22035 to store the video files + transcript files in Blockstore along with each `video` block. But how to do that without making the existing video block code + transcript code even messier than it already is will be the challenge.

**Comment by bradenmacdonald** [comment]
This is old and most likely no longer relevant to the near term development of blockstore, so I'm going to close it. The discussion will be preserved on GitHub for future reference if useful, e.g. to the learning core work.
